quarkus:
  mongodb:
    connection-string: "mongodb://localhost:27017"
    database: 'admin'
    credentials:
      password: 'cottusarm_s3cur3'
      username: 'cottusarm'

  http:
    cors: true
  banner:
    enabled: true
    path: "banner.txt"